# Generated by Django 5.0.6 on 2024-05-19 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedEvent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_id', models.CharField(default='DEFAULT_VALUE_HERE', max_length=100)),
                ('publish_room', models.CharField(max_length=100)),
                ('announcement_context', models.CharField(max_length=1500)),
                ('month_content', models.CharField(default='01', max_length=2)),
                ('day_content', models.CharField(default='01', max_length=2)),
                ('year_content', models.CharField(default='2024', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='RoomParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnamekey', models.CharField(default='DEFAULT_VALUE_HERE', max_length=100)),
                ('list_of_participant', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(default='DEFAULT_VALUE_HERE', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('year_level', models.CharField(max_length=50)),
                ('attending_course', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(default='DEFAULT_VALUE_HERE', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_code', models.CharField(max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedEvent.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'room_code'), ('teacher', 'room_name')},
            },
        ),
    ]
